version: 2
jobs:
  build:
    working_directory: /go/src/github.com/nickalie/go-kindlegen
    docker:
      - image: golang
    steps:
      - run: |
          cd /usr/bin
          wget http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz
          tar -xvzf kindlegen_linux_2.6_i386_v2_9.tar.gz
          rm kindlegen_linux_2.6_i386_v2_9.tar.gz
      - checkout
      - run: go get -t -v ./...
      - run: go test -v ./...
